version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./todolist_frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./todolist_backend
    ports:
      - "8000:8000"
    container_name: backend-docker
    restart: always
  
  # tests_backend:
  #   image: todolist_backend
  #   command:
  #     bash -c "go test ./tests"
  #   links: 
  #     - backend

  # tests_frontend:
  #   image: todolist_frontend
  #   command: 
  #     bash -c "cd ./src/components/__test__/ && npm run test"
  #   links: 
  #     - backend
      
